# Generated by Django 5.0.1 on 2024-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0002_viewapostila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('otimo', 'Otimo')], max_length=10)),
            ],
        ),
    ]
